### ISSUE TITLE
TypeError: page.client is not a function

### ISSUE THREAD

**Issue by atulmy** [alexey-pelykh/puppeteer-capture#7]
Hello, thanks for the package, was looking into something like this for video creation. Was trying to run this locally, however, facing following issue:

```
(node:1061) UnhandledPromiseRejectionWarning: TypeError: page.client is not a function
    at PuppeteerCaptureViaHeadlessExperimental.<anonymous> (/code/demo/puppeteer/puppeteer-capture/PuppeteerCaptureViaHeadlessExperimental.js:83:51)
    at step (/code/demo/puppeteer/puppeteer-capture/PuppeteerCaptureViaHeadlessExperimental.js:48:23)
    at Object.next (/code/demo/puppeteer/puppeteer-capture/PuppeteerCaptureViaHeadlessExperimental.js:29:53)
    at fulfilled (/code/demo/puppeteer/puppeteer-capture/PuppeteerCaptureViaHeadlessExperimental.js:20:58)
```

Any pointers how can I resolve this?

**Comment by alexey-pelykh** [comment]
@atulmy what `puppeteer` version are you using?

**Comment by alexey-pelykh** [comment]
https://github.com/puppeteer/puppeteer/commit/6c960115a3230e247de628b85dea7c1c02582d6d#diff-7b571f1b17991b899111f41e9844844f2fd527b4c1a775aaeb713ceb8b17959aL760-L762 There's been a change and since I have to use internal function, it stopped working

**Comment by alexey-pelykh** [comment]
It was changed with v14.4.0 release of `puppeteer` so I'll have to explicitly support that
